"""
Task 2: Write markdown file to disk with UTF-8 encoding and LF line endings

This module demonstrates task-2 of phase 2: Writing the markdown file to disk
with proper UTF-8 encoding (no BOM) and Unix LF line endings.

Task-2 depends on task-1 (content generation).
"""

from pathlib import Path
from sheep.content_generators import write_markdown_file
from sheep.observability.logging import get_logger

_logger = get_logger(__name__)

# Sample content that would come from task-1 (content generation)
# This is what generate_markdown_content() would return
SAMPLE_CONTENT = """# Artificial Intelligence Evolution

Artificial intelligence has rapidly transformed from theoretical concept to practical application across industries. Machine learning algorithms now power recommendation systems, autonomous vehicles, and medical diagnostic tools. The field continues to evolve with advances in neural networks and large language models.
"""

MARKDOWN_FILENAME = "test-o09hnk.md"


def task_2_write_markdown_file(content: str) -> str:
    """
    Task 2: Write markdown file to disk with UTF-8 encoding and LF line endings.

    Args:
        content: Generated markdown content (from task-1)

    Returns:
        Path to the written file

    Raises:
        ValueError: If content is invalid
        IOError: If file operations fail
    """
    _logger.info(f"Task 2: Writing markdown file {MARKDOWN_FILENAME}")

    try:
        # Call write_markdown_file to write content with proper encoding
        filepath = write_markdown_file(content, MARKDOWN_FILENAME)
        _logger.debug(f"File written to: {filepath}")

        # Verify file exists at expected path
        assert Path(filepath).exists(), f"File {filepath} does not exist"
        _logger.info(f"File verified at: {filepath}")

        # Verify file size is reasonable (~500 bytes for H1 heading + 2-3 sentences)
        file_size = Path(filepath).stat().st_size
        assert file_size > 0, f"File {filepath} is empty"
        _logger.debug(f"File size: {file_size} bytes")

        # Verify content matches what was written
        written_content = Path(filepath).read_text(encoding='utf-8')
        assert written_content == content, "Written content does not match input content"
        _logger.info("Content verification passed")

        # Verify UTF-8 encoding without BOM
        binary_content = Path(filepath).read_bytes()
        assert not binary_content.startswith(b'\xef\xbb\xbf'), "File contains UTF-8 BOM"
        _logger.info("UTF-8 encoding (no BOM) verified")

        # Verify LF line endings (no CRLF)
        assert b'\r\n' not in binary_content, "File contains CRLF line endings"
        assert b'\r' not in binary_content, "File contains CR line endings"
        _logger.info("LF line endings verified")

        # Verify trailing newline
        assert written_content.endswith('\n'), "File does not end with newline"
        _logger.info("Trailing newline verified")

        _logger.info(f"Task 2 complete: {MARKDOWN_FILENAME} written successfully")
        return filepath

    except Exception as e:
        _logger.error(f"Task 2 failed: {e}")
        raise


def task_2_with_generated_content(generated_content: str) -> str:
    """
    Wrapper to call task-2 with content from task-1.

    Args:
        generated_content: Content generated by task-1 (generate_markdown_content)

    Returns:
        Path to the written file
    """
    return task_2_write_markdown_file(generated_content)


if __name__ == "__main__":
    # Execute task 2 with sample content
    result = task_2_write_markdown_file(SAMPLE_CONTENT)
    print(f"Task 2 completed successfully: {result}")
