"""Implementation for feature 296: Create markdown file test-v4dx46.md with title and prose content.

This module orchestrates the creation of a markdown file following the established pattern
from 290+ preceding features. The file is created with:
- Exact filename: test-v4dx46.md
- H1 markdown heading as title (auto-generated by Claude API)
- Exactly 2-3 sentences of prose content (auto-generated by Claude API)
- UTF-8 encoding without BOM
- Unix LF line endings
- File size approximately 400-600 bytes
- Git staging, commit, and push operations with conventional message format
"""

from pathlib import Path

from sheep.content_generators import create_markdown_file
from sheep.observability.logging import get_logger

_logger = get_logger(__name__)

# Feature metadata
FEATURE_NUMBER = 296
FEATURE_NAME = "markdown-file-creation-v4dx46"
MARKDOWN_FILENAME = "test-v4dx46.md"
