"""Implementation for feature 294: Create markdown file test-xvaf7y.md with title and prose content.

This module orchestrates the creation of a markdown file following the established pattern
from 289+ preceding features. The file is created with:
- Exact filename: test-xvaf7y.md
- H1 markdown heading as title (auto-generated by Claude API)
- Exactly 2-3 sentences of prose content (auto-generated by Claude API)
- UTF-8 encoding without BOM
- Unix LF line endings
- File size approximately 250-600 bytes
- Git staging, commit, and push operations with conventional message format
"""

from pathlib import Path

from sheep.content_generators import create_markdown_file
from sheep.observability.logging import get_logger

_logger = get_logger(__name__)

# Feature metadata
FEATURE_NUMBER = 294
FEATURE_NAME = "markdown-file-creation-d5f4d7"
MARKDOWN_FILENAME = "test-xvaf7y.md"


def create_test_xvaf7y_markdown_file(repo_path: str | None = None) -> dict[str, str]:
    """
    Create markdown file for feature 294.

    Orchestrates the complete workflow using the sheep.content_generators orchestration function:
    1. Generate valid markdown content via Claude API (H1 heading + 2-3 sentences)
    2. Write file to repository root with UTF-8 encoding
    3. Validate file meets all specification requirements
    4. Stage and commit with conventional message
    5. Push to remote feature branch

    Args:
        repo_path: Path to git repository (defaults to current directory).

    Returns:
        Dictionary containing:
        - filepath: Full path to created file
        - content: Markdown content (H1 heading + prose)
        - commit_message: Git commit message used
        - push_result: Result from git push

    Raises:
        ValueError: If content or file is invalid
        IOError: If file operations fail
        Exception: If git operations fail or LLM API fails
    """
    if repo_path is None:
        repo_path = str(Path.cwd())

    _logger.info(
        f"Creating feature {FEATURE_NUMBER} markdown file: {MARKDOWN_FILENAME}"
    )

    try:
        # Call the orchestration function from sheep.content_generators
        # This handles: content generation, file creation, validation, commit, and push
        result = create_markdown_file(
            filename=MARKDOWN_FILENAME,
            repo_path=repo_path,
            feature_number=FEATURE_NUMBER,
        )

        _logger.info(
            f"Successfully created and published feature {FEATURE_NUMBER}: {MARKDOWN_FILENAME}"
        )
        _logger.debug(f"Result: {result}")

        return result

    except Exception as e:
        _logger.error(f"Failed to create feature {FEATURE_NUMBER} markdown file: {e}")
        raise


def main() -> int:
    """
    Main entry point for feature 294 markdown file creation.

    Returns:
        0 on success, 1 on failure.
    """
    try:
        _logger.info("Starting feature 294: markdown-file-creation-d5f4d7")
        result = create_test_xvaf7y_markdown_file()
        _logger.info(f"Feature 294 completed successfully: {result['filepath']}")
        return 0
    except Exception as e:
        _logger.error(f"Feature 294 failed: {e}")
        return 1


if __name__ == "__main__":
    exit(main())
